In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

functions = [i for i in dir(pd.DatetimeIndex) if i[:1] != '_']

for i, v in enumerate(functions):
    print(i, v)

0 T
1 all
2 any
3 append
4 argmax
5 argmin
6 argsort
7 array
8 asi8
9 asof
10 asof_locs
11 astype
12 ceil
13 copy
14 date
15 day
16 day_name
17 day_of_week
18 day_of_year
19 dayofweek
20 dayofyear
21 days_in_month
22 daysinmonth
23 delete
24 difference
25 drop
26 drop_duplicates
27 droplevel
28 dropna
29 dtype
30 duplicated
31 empty
32 equals
33 factorize
34 fillna
35 floor
36 format
37 freq
38 freqstr
39 get_indexer
40 get_indexer_for
41 get_indexer_non_unique
42 get_level_values
43 get_loc
44 get_slice_bound
45 get_value
46 groupby
47 has_duplicates
48 hasnans
49 holds_integer
50 hour
51 identical
52 indexer_at_time
53 indexer_between_time
54 inferred_freq
55 inferred_type
56 insert
57 intersection
58 is_
59 is_all_dates
60 is_boolean
61 is_categorical
62 is_floating
63 is_integer
64 is_interval
65 is_leap_year
66 is_mixed
67 is_monotonic
68 is_monotonic_decreasing
69 is_monotonic_increasing
70 is_month_end
71 is_month_start
72 is_normalized
73 is_numeric
74 is_object
75 is_quarter_e

In [4]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data

DatetimeIndex(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04',
               '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08',
               '2005-01-09', '2005-01-10'],
              dtype='datetime64[ns]', freq='D')

In [5]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.T

DatetimeIndex(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04',
               '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08',
               '2005-01-09', '2005-01-10'],
              dtype='datetime64[ns]', freq='D')

In [6]:
data = pd.Index([1,2,3])
data.all()

True

In [7]:
data = pd.Index([0,1])
data.any()

True

In [8]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.append(pd.date_range('1/12/2005', periods=2, freq='1D'))

DatetimeIndex(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04',
               '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08',
               '2005-01-09', '2005-01-10', '2005-01-12', '2005-01-13'],
              dtype='datetime64[ns]', freq=None)

In [9]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
print(data)
data[data.argmax()]

DatetimeIndex(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04',
               '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08',
               '2005-01-09', '2005-01-10'],
              dtype='datetime64[ns]', freq='D')


Timestamp('2005-01-10 00:00:00', freq='D')

In [10]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
print(data)
data[data.argmin()]

DatetimeIndex(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04',
               '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08',
               '2005-01-09', '2005-01-10'],
              dtype='datetime64[ns]', freq='D')


Timestamp('2005-01-01 00:00:00', freq='D')

In [11]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
print(data)
data[data.argsort(ascending=False)]

DatetimeIndex(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04',
               '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08',
               '2005-01-09', '2005-01-10'],
              dtype='datetime64[ns]', freq='D')


DatetimeIndex(['2005-01-10', '2005-01-09', '2005-01-08', '2005-01-07',
               '2005-01-06', '2005-01-05', '2005-01-04', '2005-01-03',
               '2005-01-02', '2005-01-01'],
              dtype='datetime64[ns]', freq=None)

In [12]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.array

<DatetimeArray>
['2005-01-01 00:00:00', '2005-01-02 00:00:00', '2005-01-03 00:00:00',
 '2005-01-04 00:00:00', '2005-01-05 00:00:00', '2005-01-06 00:00:00',
 '2005-01-07 00:00:00', '2005-01-08 00:00:00', '2005-01-09 00:00:00',
 '2005-01-10 00:00:00']
Length: 10, dtype: datetime64[ns]

In [13]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.asi8

array([1104537600000000000, 1104624000000000000, 1104710400000000000,
       1104796800000000000, 1104883200000000000, 1104969600000000000,
       1105056000000000000, 1105142400000000000, 1105228800000000000,
       1105315200000000000])

In [14]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.asof(pd.Timestamp(2020, 3, 14))

Timestamp('2005-01-10 00:00:00', freq='D')

In [15]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.asof_locs.__doc__

'\n        Return the locations (indices) of labels in the index.\n\n        As in the `asof` function, if the label (a particular entry in\n        `where`) is not in the index, the latest index label up to the\n        passed label is chosen and its index returned.\n\n        If all of the labels in the index are later than a label in `where`,\n        -1 is returned.\n\n        `mask` is used to ignore NA values in the index during calculation.\n\n        Parameters\n        ----------\n        where : Index\n            An Index consisting of an array of timestamps.\n        mask : np.ndarray[bool]\n            Array of booleans denoting where values in the original\n            data are not NA.\n\n        Returns\n        -------\n        np.ndarray[np.intp]\n            An array of locations (indices) of the labels from the Index\n            which correspond to the return values of the `asof` function\n            for every element in `where`.\n        '

In [16]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.astype(np.object)

/var/folders/7v/1c76ypv54yx261vygq63_47w0000gp/T/ipykernel_4335/713149380.py:2: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  data.astype(np.object)


Index([2005-01-01 00:00:00, 2005-01-02 00:00:00, 2005-01-03 00:00:00,
       2005-01-04 00:00:00, 2005-01-05 00:00:00, 2005-01-06 00:00:00,
       2005-01-07 00:00:00, 2005-01-08 00:00:00, 2005-01-09 00:00:00,
       2005-01-10 00:00:00],
      dtype='object')

In [17]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.ceil(freq='2D')

DatetimeIndex(['2005-01-01', '2005-01-03', '2005-01-03', '2005-01-05',
               '2005-01-05', '2005-01-07', '2005-01-07', '2005-01-09',
               '2005-01-09', '2005-01-11'],
              dtype='datetime64[ns]', freq=None)

In [18]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
x = data.copy(name="copied")
x

DatetimeIndex(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04',
               '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08',
               '2005-01-09', '2005-01-10'],
              dtype='datetime64[ns]', name='copied', freq='D')

In [19]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.date

array([datetime.date(2005, 1, 1), datetime.date(2005, 1, 2),
       datetime.date(2005, 1, 3), datetime.date(2005, 1, 4),
       datetime.date(2005, 1, 5), datetime.date(2005, 1, 6),
       datetime.date(2005, 1, 7), datetime.date(2005, 1, 8),
       datetime.date(2005, 1, 9), datetime.date(2005, 1, 10)],
      dtype=object)

In [20]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.day

Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

In [21]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.day_name()

Index(['Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday',
       'Friday', 'Saturday', 'Sunday', 'Monday'],
      dtype='object')

In [22]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.day_of_week

Int64Index([5, 6, 0, 1, 2, 3, 4, 5, 6, 0], dtype='int64')

In [23]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.day_of_year

Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

In [24]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.dayofweek

Int64Index([5, 6, 0, 1, 2, 3, 4, 5, 6, 0], dtype='int64')

In [25]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.dayofyear

Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

In [26]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.days_in_month

Int64Index([31, 31, 31, 31, 31, 31, 31, 31, 31, 31], dtype='int64')

In [27]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.daysinmonth

Int64Index([31, 31, 31, 31, 31, 31, 31, 31, 31, 31], dtype='int64')

In [28]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.delete([0,-1])

DatetimeIndex(['2005-01-02', '2005-01-03', '2005-01-04', '2005-01-05',
               '2005-01-06', '2005-01-07', '2005-01-08', '2005-01-09'],
              dtype='datetime64[ns]', freq=None)

In [29]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.difference(pd.DatetimeIndex(data=pd.date_range('1/5/2005', periods=10, freq='1D')))


DatetimeIndex(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04'], dtype='datetime64[ns]', freq=None)

In [30]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data = data.drop(['2005-01-01', '2005-01-02'])
data

DatetimeIndex(['2005-01-03', '2005-01-04', '2005-01-05', '2005-01-06',
               '2005-01-07', '2005-01-08', '2005-01-09', '2005-01-10'],
              dtype='datetime64[ns]', freq='D')

In [31]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data = data.append(data)
print(data)
data.drop_duplicates()

DatetimeIndex(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04',
               '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08',
               '2005-01-09', '2005-01-10', '2005-01-01', '2005-01-02',
               '2005-01-03', '2005-01-04', '2005-01-05', '2005-01-06',
               '2005-01-07', '2005-01-08', '2005-01-09', '2005-01-10'],
              dtype='datetime64[ns]', freq=None)


DatetimeIndex(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04',
               '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08',
               '2005-01-09', '2005-01-10'],
              dtype='datetime64[ns]', freq=None)

In [32]:
mi = pd.MultiIndex.from_arrays([[1, 2], [3, 4], [5, 6]], names=['x', 'y', 'z'])
mi.droplevel(2)

MultiIndex([(1, 3),
            (2, 4)],
           names=['x', 'y'])

In [33]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data = data.append(pd.Index([np.nan, np.nan]))
print(data)
data.dropna()

DatetimeIndex(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04',
               '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08',
               '2005-01-09', '2005-01-10',        'NaT',        'NaT'],
              dtype='datetime64[ns]', freq=None)


DatetimeIndex(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04',
               '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08',
               '2005-01-09', '2005-01-10'],
              dtype='datetime64[ns]', freq=None)

In [34]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.dtype

dtype('<M8[ns]')

In [35]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data = data.append(pd.DatetimeIndex(['2005-01-01']))
data.duplicated()

array([False, False, False, False, False, False, False, False, False,
       False,  True])

In [36]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.empty

False

In [37]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.equals(data)


True

In [38]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.factorize()

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 DatetimeIndex(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04',
                '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08',
                '2005-01-09', '2005-01-10'],
               dtype='datetime64[ns]', freq='D'))

In [39]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.fillna()

DatetimeIndex(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04',
               '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08',
               '2005-01-09', '2005-01-10'],
              dtype='datetime64[ns]', freq='D')

In [40]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.floor(freq='3D')

DatetimeIndex(['2004-12-31', '2004-12-31', '2005-01-03', '2005-01-03',
               '2005-01-03', '2005-01-06', '2005-01-06', '2005-01-06',
               '2005-01-09', '2005-01-09'],
              dtype='datetime64[ns]', freq=None)

In [41]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.format()

['2005-01-01',
 '2005-01-02',
 '2005-01-03',
 '2005-01-04',
 '2005-01-05',
 '2005-01-06',
 '2005-01-07',
 '2005-01-08',
 '2005-01-09',
 '2005-01-10']

In [42]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.freq

<Day>

In [43]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.freqstr

'D'

In [44]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.get_indexer([1,2,3])

array([-1, -1, -1])

In [45]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.get_indexer_for([1,2,3])

array([-1, -1, -1])

In [46]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.get_indexer_non_unique([1,2,3,4-5])

(array([-1, -1, -1, -1]), array([0, 1, 2, 3]))

In [47]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.get_level_values(0)

DatetimeIndex(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04',
               '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08',
               '2005-01-09', '2005-01-10'],
              dtype='datetime64[ns]', freq='D')

In [48]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.get_loc('2005-01-10')


9

In [49]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
print(data)
print(data.get_slice_bound('2005-01-04', side="right"))
print(data.get_slice_bound('2005-01-04', side="left"))

DatetimeIndex(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04',
               '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08',
               '2005-01-09', '2005-01-10'],
              dtype='datetime64[ns]', freq='D')
4
3


In [50]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.get_value.__doc__


"\n        Fast lookup of value from 1-dimensional ndarray.\n\n        Only use this if you know what you're doing.\n\n        Returns\n        -------\n        scalar or Series\n        "

In [51]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.groupby('2005-01-10')

/var/folders/7v/1c76ypv54yx261vygq63_47w0000gp/T/ipykernel_4335/3387258225.py:2: FutureWarning: Allowing scalars in the Categorical constructor is deprecated and will raise in a future version.  Use `[value]` instead
  data.groupby('2005-01-10')


{'2005-01-10': [2005-01-01 00:00:00]}

In [52]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.has_duplicates

False

In [53]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.hasnans

False

In [54]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.holds_integer()

False

In [55]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
data.hour

Int64Index([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype='int64')

In [56]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))
print(data.identical(pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1D'))))
print(data.identical(pd.DatetimeIndex(data=pd.date_range('1/2/2005', periods=10, freq='1D'))))

True
False


In [57]:
data = pd.DatetimeIndex(data=pd.date_range('1/1/2005', periods=10, freq='1H'))
data.indexer_at_time('2005-01-01 06:00:00')

array([6])

In [79]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1H'))
print("date : \n", data)
index = data.indexer_between_time("03:00", "00:08")
data[index]

date : 
 DatetimeIndex(['2005-01-01 00:00:00', '2005-01-01 01:00:00',
               '2005-01-01 02:00:00', '2005-01-01 03:00:00',
               '2005-01-01 04:00:00', '2005-01-01 05:00:00',
               '2005-01-01 06:00:00', '2005-01-01 07:00:00',
               '2005-01-01 08:00:00', '2005-01-01 09:00:00'],
              dtype='datetime64[ns]', freq='H')


DatetimeIndex(['2005-01-01 00:00:00', '2005-01-01 03:00:00',
               '2005-01-01 04:00:00', '2005-01-01 05:00:00',
               '2005-01-01 06:00:00', '2005-01-01 07:00:00',
               '2005-01-01 08:00:00', '2005-01-01 09:00:00'],
              dtype='datetime64[ns]', freq=None)

In [88]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.inferred_freq

'D'

In [90]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.inferred_type

'datetime64'

In [95]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=20, freq='1D'))
print(data.is_(data.copy()))
print(data.is_(data))

False
True


In [102]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.is_all_dates

/var/folders/7v/1c76ypv54yx261vygq63_47w0000gp/T/ipykernel_4335/3237038260.py:2: FutureWarning: Index.is_all_dates is deprecated, will be removed in a future version. check index.inferred_type instead.
  data.is_all_dates


True

In [104]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.is_boolean()

False

In [106]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.is_floating()

False

In [108]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.is_integer()

False

In [110]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.is_interval()

False

In [114]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.is_leap_year

array([False, False, False, False, False, False, False, False, False,
       False])

In [118]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.is_mixed()

/var/folders/7v/1c76ypv54yx261vygq63_47w0000gp/T/ipykernel_4335/4134202256.py:2: FutureWarning: Index.is_mixed is deprecated and will be removed in a future version. Check index.inferred_type directly instead.
  data.is_mixed()


False

In [120]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.is_monotonic

/var/folders/7v/1c76ypv54yx261vygq63_47w0000gp/T/ipykernel_4335/2216058608.py:2: FutureWarning: is_monotonic is deprecated and will be removed in a future version. Use is_monotonic_increasing instead.
  data.is_monotonic


True

In [122]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.is_monotonic_decreasing

False

In [123]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.is_monotonic_increasing

True

In [133]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='10D'))
data.is_month_end

array([False, False, False,  True, False, False, False, False, False,
       False])

In [134]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='10D'))
data.is_month_start

array([ True, False, False, False, False, False, False, False, False,
        True])

In [136]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.is_normalized

True

In [138]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.is_numeric()

False

In [140]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.is_object()

False

In [147]:
data = pd.DatetimeIndex(pd.date_range('03/30/2005', periods=10))
data.is_quarter_end

array([False,  True, False, False, False, False, False, False, False,
       False])

In [148]:
data = pd.DatetimeIndex(pd.date_range('03/30/2005', periods=10))
data.is_quarter_start

array([False, False,  True, False, False, False, False, False, False,
       False])

In [155]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10))
data.is_type_compatible(np.datetime64)

/var/folders/7v/1c76ypv54yx261vygq63_47w0000gp/T/ipykernel_4335/3908112492.py:2: FutureWarning: DatetimeIndex.is_type_compatible is deprecated and will be removed in a future version.
  data.is_type_compatible(np.datetime64)


False

In [159]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10))
data.is_unique

True

In [161]:
data = pd.DatetimeIndex(pd.date_range('25/12/2005', periods=10))
data.is_year_end

/var/folders/7v/1c76ypv54yx261vygq63_47w0000gp/T/ipykernel_4335/1560639415.py:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  data = pd.DatetimeIndex(pd.date_range('25/12/2005', periods=10))


array([False, False, False, False, False, False,  True, False, False,
       False])

In [162]:
data = pd.DatetimeIndex(pd.date_range('25/12/2005', periods=10))
data.is_year_start

/var/folders/7v/1c76ypv54yx261vygq63_47w0000gp/T/ipykernel_4335/3186565545.py:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  data = pd.DatetimeIndex(pd.date_range('25/12/2005', periods=10))


array([False, False, False, False, False, False, False,  True, False,
       False])

In [169]:
data = pd.DatetimeIndex(pd.date_range('25/12/2005', periods=10))
print(data.isin(['2005-12-27']))
print(data.isin(['2005-10-27']))

[False False  True False False False False False False False]
[False False False False False False False False False False]


/var/folders/7v/1c76ypv54yx261vygq63_47w0000gp/T/ipykernel_4335/205097091.py:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  data = pd.DatetimeIndex(pd.date_range('25/12/2005', periods=10))


In [172]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D')).append(pd.DatetimeIndex([np.nan]))
data.isna()

array([False, False, False, False, False, False, False, False, False,
       False,  True])

In [174]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D')).append(pd.DatetimeIndex([np.nan]))
data.isnull()

array([False, False, False, False, False, False, False, False, False,
       False,  True])

In [178]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.isocalendar()

year  week  day
2005-01-01  2004    53    6
2005-01-02  2004    53    7
2005-01-03  2005     1    1
2005-01-04  2005     1    2
2005-01-05  2005     1    3
2005-01-06  2005     1    4
2005-01-07  2005     1    5
2005-01-08  2005     1    6
2005-01-09  2005     1    7
2005-01-10  2005     2    1

In [187]:
data = pd.DatetimeIndex([pd.date_range('1/1/2005', periods=10, freq='1D')])
data.item()

<DatetimeArray>
['2005-01-01 00:00:00', '2005-01-02 00:00:00', '2005-01-03 00:00:00',
 '2005-01-04 00:00:00', '2005-01-05 00:00:00', '2005-01-06 00:00:00',
 '2005-01-07 00:00:00', '2005-01-08 00:00:00', '2005-01-09 00:00:00',
 '2005-01-10 00:00:00']
Length: 10, dtype: datetime64[ns]

In [223]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.join(data)

DatetimeIndex(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04',
               '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08',
               '2005-01-09', '2005-01-10'],
              dtype='datetime64[ns]', freq='D')

In [230]:
def my_f(p):
    return p.shift(10)

data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.map(my_f)

DatetimeIndex(['2005-01-11', '2005-01-12', '2005-01-13', '2005-01-14',
               '2005-01-15', '2005-01-16', '2005-01-17', '2005-01-18',
               '2005-01-19', '2005-01-20'],
              dtype='datetime64[ns]', freq='D')

In [232]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.max()

Timestamp('2005-01-10 00:00:00', freq='D')

In [234]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.mean()

Timestamp('2005-01-05 12:00:00', freq='D')

In [236]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.memory_usage()

80

In [237]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.microsecond

Int64Index([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype='int64')

In [238]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.min()

Timestamp('2005-01-01 00:00:00', freq='D')

In [241]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.minute

Int64Index([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype='int64')

In [243]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='10D'))
data.month

Int64Index([1, 1, 1, 1, 2, 2, 3, 3, 3, 4], dtype='int64')

In [245]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='10D'))
data.month_name()

Index(['January', 'January', 'January', 'January', 'February', 'February',
       'March', 'March', 'March', 'April'],
      dtype='object')

In [250]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.name

In [253]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.names

FrozenList([None])

In [255]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.nanosecond

Int64Index([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype='int64')

In [258]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.nbytes

80

In [259]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.ndim

1

In [262]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.nlevels

1

In [265]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.normalize()

DatetimeIndex(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04',
               '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08',
               '2005-01-09', '2005-01-10'],
              dtype='datetime64[ns]', freq='D')

In [266]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D')).append(pd.DatetimeIndex([np.nan]))
data.notna()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False])

In [268]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D')).append(pd.DatetimeIndex([np.nan]))
data.notnull()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False])

In [269]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.nunique()

10

In [273]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.putmask(mask=data, value=np.arange(10))

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='object')

In [274]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.quarter

Int64Index([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype='int64')

In [278]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.ravel('C')

/var/folders/7v/1c76ypv54yx261vygq63_47w0000gp/T/ipykernel_4335/2128156397.py:2: FutureWarning: Index.ravel returning ndarray is deprecated; in a future version this will return a view on self.
  data.ravel('C')


array(['2005-01-01T00:00:00.000000000', '2005-01-02T00:00:00.000000000',
       '2005-01-03T00:00:00.000000000', '2005-01-04T00:00:00.000000000',
       '2005-01-05T00:00:00.000000000', '2005-01-06T00:00:00.000000000',
       '2005-01-07T00:00:00.000000000', '2005-01-08T00:00:00.000000000',
       '2005-01-09T00:00:00.000000000', '2005-01-10T00:00:00.000000000'],
      dtype='datetime64[ns]')

In [280]:
data = pd.DataFrame(pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D')))
data.reindex()

0
0 2005-01-01
1 2005-01-02
2 2005-01-03
3 2005-01-04
4 2005-01-05
5 2005-01-06
6 2005-01-07
7 2005-01-08
8 2005-01-09
9 2005-01-10

In [281]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.rename("iqrorjoncoder")

DatetimeIndex(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04',
               '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08',
               '2005-01-09', '2005-01-10'],
              dtype='datetime64[ns]', name='iqrorjoncoder', freq='D')

In [283]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.repeat(2)

DatetimeIndex(['2005-01-01', '2005-01-01', '2005-01-02', '2005-01-02',
               '2005-01-03', '2005-01-03', '2005-01-04', '2005-01-04',
               '2005-01-05', '2005-01-05', '2005-01-06', '2005-01-06',
               '2005-01-07', '2005-01-07', '2005-01-08', '2005-01-08',
               '2005-01-09', '2005-01-09', '2005-01-10', '2005-01-10'],
              dtype='datetime64[ns]', freq=None)

In [3]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.resolution

'day'

In [11]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.round(freq='5D')

DatetimeIndex(['2005-01-02', '2005-01-02', '2005-01-02', '2005-01-02',
               '2005-01-07', '2005-01-07', '2005-01-07', '2005-01-07',
               '2005-01-07', '2005-01-12'],
              dtype='datetime64[ns]', freq=None)

In [15]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.searchsorted(value='1/12/2005')

10

In [21]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='3S'))
data.second

Int64Index([0, 3, 6, 9, 12, 15, 18, 21, 24, 27], dtype='int64')

In [26]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.set_names(names='iqrorjoncoder')

DatetimeIndex(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04',
               '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08',
               '2005-01-09', '2005-01-10'],
              dtype='datetime64[ns]', name='iqrorjoncoder', freq='D')

In [49]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.set_value.__doc__

"\n        Fast lookup of value from 1-dimensional ndarray.\n\n        .. deprecated:: 1.0\n\n        Notes\n        -----\n        Only use this if you know what you're doing.\n        "

In [51]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.shape

(10,)

In [53]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.shift(2)

DatetimeIndex(['2005-01-03', '2005-01-04', '2005-01-05', '2005-01-06',
               '2005-01-07', '2005-01-08', '2005-01-09', '2005-01-10',
               '2005-01-11', '2005-01-12'],
              dtype='datetime64[ns]', freq='D')

In [55]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.size

10

In [59]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='2D'))
data.slice_indexer()

slice(0, 10, None)

In [60]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.slice_locs()

(0, 10)

In [65]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.snap(freq='2M')

DatetimeIndex(['2004-12-31', '2004-12-31', '2004-12-31', '2004-12-31',
               '2004-12-31', '2004-12-31', '2004-12-31', '2004-12-31',
               '2004-12-31', '2004-12-31'],
              dtype='datetime64[ns]', freq=None)

In [74]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.sort.__doc__

'\n        Use sort_values instead.\n        '

In [78]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.sort_values(ascending=False)

DatetimeIndex(['2005-01-10', '2005-01-09', '2005-01-08', '2005-01-07',
               '2005-01-06', '2005-01-05', '2005-01-04', '2005-01-03',
               '2005-01-02', '2005-01-01'],
              dtype='datetime64[ns]', freq='-1D')

In [82]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.sortlevel(ascending=False)

(DatetimeIndex(['2005-01-10', '2005-01-09', '2005-01-08', '2005-01-07',
                '2005-01-06', '2005-01-05', '2005-01-04', '2005-01-03',
                '2005-01-02', '2005-01-01'],
               dtype='datetime64[ns]', freq='-1D'),
 array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int64))

In [85]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.std()

Timedelta('3 days 00:39:48.990594023')

In [104]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.strftime('%d--%m--%Y')

Index(['01--01--2005', '02--01--2005', '03--01--2005', '04--01--2005',
       '05--01--2005', '06--01--2005', '07--01--2005', '08--01--2005',
       '09--01--2005', '10--01--2005'],
      dtype='object')

In [112]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.symmetric_difference(data.append([pd.Index([1, np.nan])]))

Index([1.0, nan], dtype='object')

In [116]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.take(indices=[0,2,5])

DatetimeIndex(['2005-01-01', '2005-01-03', '2005-01-06'], dtype='datetime64[ns]', freq=None)

In [125]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1H'))
data.time

array([datetime.time(0, 0), datetime.time(1, 0), datetime.time(2, 0),
       datetime.time(3, 0), datetime.time(4, 0), datetime.time(5, 0),
       datetime.time(6, 0), datetime.time(7, 0), datetime.time(8, 0),
       datetime.time(9, 0)], dtype=object)

In [128]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1H'))
data.timetz

array([datetime.time(0, 0), datetime.time(1, 0), datetime.time(2, 0),
       datetime.time(3, 0), datetime.time(4, 0), datetime.time(5, 0),
       datetime.time(6, 0), datetime.time(7, 0), datetime.time(8, 0),
       datetime.time(9, 0)], dtype=object)

In [130]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.to_flat_index()

DatetimeIndex(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04',
               '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08',
               '2005-01-09', '2005-01-10'],
              dtype='datetime64[ns]', freq='D')

In [135]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.to_frame(index=True)

0
2005-01-01 2005-01-01
2005-01-02 2005-01-02
2005-01-03 2005-01-03
2005-01-04 2005-01-04
2005-01-05 2005-01-05
2005-01-06 2005-01-06
2005-01-07 2005-01-07
2005-01-08 2005-01-08
2005-01-09 2005-01-09
2005-01-10 2005-01-10

In [138]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.to_julian_date()

Float64Index([2453371.5, 2453372.5, 2453373.5, 2453374.5, 2453375.5, 2453376.5,
              2453377.5, 2453378.5, 2453379.5, 2453380.5],
             dtype='float64')

In [141]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.to_list()

[Timestamp('2005-01-01 00:00:00', freq='D'),
 Timestamp('2005-01-02 00:00:00', freq='D'),
 Timestamp('2005-01-03 00:00:00', freq='D'),
 Timestamp('2005-01-04 00:00:00', freq='D'),
 Timestamp('2005-01-05 00:00:00', freq='D'),
 Timestamp('2005-01-06 00:00:00', freq='D'),
 Timestamp('2005-01-07 00:00:00', freq='D'),
 Timestamp('2005-01-08 00:00:00', freq='D'),
 Timestamp('2005-01-09 00:00:00', freq='D'),
 Timestamp('2005-01-10 00:00:00', freq='D')]

In [144]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.to_native_types()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_6072\3857221366.py:2: FutureWarning: The 'to_native_types' method is deprecated and will be removed in a future version. Use 'astype(str)' instead.
  data.to_native_types()


array(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04',
       '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08',
       '2005-01-09', '2005-01-10'], dtype=object)

In [151]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
print(data.to_numpy())
print(data.to_numpy().dtype)

['2005-01-01T00:00:00.000000000' '2005-01-02T00:00:00.000000000'
 '2005-01-03T00:00:00.000000000' '2005-01-04T00:00:00.000000000'
 '2005-01-05T00:00:00.000000000' '2005-01-06T00:00:00.000000000'
 '2005-01-07T00:00:00.000000000' '2005-01-08T00:00:00.000000000'
 '2005-01-09T00:00:00.000000000' '2005-01-10T00:00:00.000000000']
datetime64[ns]


In [156]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.to_period(freq='1H')

PeriodIndex(['2005-01-01 00:00', '2005-01-02 00:00', '2005-01-03 00:00',
             '2005-01-04 00:00', '2005-01-05 00:00', '2005-01-06 00:00',
             '2005-01-07 00:00', '2005-01-08 00:00', '2005-01-09 00:00',
             '2005-01-10 00:00'],
            dtype='period[H]')

In [164]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.to_perioddelta(freq='1M')

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_6072\1863402186.py:2: FutureWarning: to_perioddelta is deprecated and will be removed in a future version. Use `dtindex - dtindex.to_period(freq).to_timestamp()` instead.
  data.to_perioddelta(freq='1M')


TimedeltaIndex(['0 days', '1 days', '2 days', '3 days', '4 days', '5 days',
                '6 days', '7 days', '8 days', '9 days'],
               dtype='timedelta64[ns]', freq=None)

In [171]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
print(data.to_pydatetime())
print(type(data.to_pydatetime()[0]))

[datetime.datetime(2005, 1, 1, 0, 0) datetime.datetime(2005, 1, 2, 0, 0)
 datetime.datetime(2005, 1, 3, 0, 0) datetime.datetime(2005, 1, 4, 0, 0)
 datetime.datetime(2005, 1, 5, 0, 0) datetime.datetime(2005, 1, 6, 0, 0)
 datetime.datetime(2005, 1, 7, 0, 0) datetime.datetime(2005, 1, 8, 0, 0)
 datetime.datetime(2005, 1, 9, 0, 0) datetime.datetime(2005, 1, 10, 0, 0)]
<class 'datetime.datetime'>


In [177]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.to_series()

2005-01-01   2005-01-01
2005-01-02   2005-01-02
2005-01-03   2005-01-03
2005-01-04   2005-01-04
2005-01-05   2005-01-05
2005-01-06   2005-01-06
2005-01-07   2005-01-07
2005-01-08   2005-01-08
2005-01-09   2005-01-09
2005-01-10   2005-01-10
Freq: D, dtype: datetime64[ns]

In [179]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.tolist()

[Timestamp('2005-01-01 00:00:00', freq='D'),
 Timestamp('2005-01-02 00:00:00', freq='D'),
 Timestamp('2005-01-03 00:00:00', freq='D'),
 Timestamp('2005-01-04 00:00:00', freq='D'),
 Timestamp('2005-01-05 00:00:00', freq='D'),
 Timestamp('2005-01-06 00:00:00', freq='D'),
 Timestamp('2005-01-07 00:00:00', freq='D'),
 Timestamp('2005-01-08 00:00:00', freq='D'),
 Timestamp('2005-01-09 00:00:00', freq='D'),
 Timestamp('2005-01-10 00:00:00', freq='D')]

In [182]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.transpose()

DatetimeIndex(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04',
               '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08',
               '2005-01-09', '2005-01-10'],
              dtype='datetime64[ns]', freq='D')

In [200]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D', tz='Asia/Tashkent'))
data.tz

<DstTzInfo 'Asia/Tashkent' LMT+4:37:00 STD>

In [202]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D', tz='Asia/Tashkent'))
print(data)
print(data.tz_convert('US/Central'))

DatetimeIndex(['2005-01-01 00:00:00+05:00', '2005-01-02 00:00:00+05:00',
               '2005-01-03 00:00:00+05:00', '2005-01-04 00:00:00+05:00',
               '2005-01-05 00:00:00+05:00', '2005-01-06 00:00:00+05:00',
               '2005-01-07 00:00:00+05:00', '2005-01-08 00:00:00+05:00',
               '2005-01-09 00:00:00+05:00', '2005-01-10 00:00:00+05:00'],
              dtype='datetime64[ns, Asia/Tashkent]', freq='D')
DatetimeIndex(['2004-12-31 13:00:00-06:00', '2005-01-01 13:00:00-06:00',
               '2005-01-02 13:00:00-06:00', '2005-01-03 13:00:00-06:00',
               '2005-01-04 13:00:00-06:00', '2005-01-05 13:00:00-06:00',
               '2005-01-06 13:00:00-06:00', '2005-01-07 13:00:00-06:00',
               '2005-01-08 13:00:00-06:00', '2005-01-09 13:00:00-06:00'],
              dtype='datetime64[ns, US/Central]', freq='D')


In [209]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1H'))
data.tz_localize(tz='US/Eastern')

DatetimeIndex(['2005-01-01 00:00:00-05:00', '2005-01-01 01:00:00-05:00',
               '2005-01-01 02:00:00-05:00', '2005-01-01 03:00:00-05:00',
               '2005-01-01 04:00:00-05:00', '2005-01-01 05:00:00-05:00',
               '2005-01-01 06:00:00-05:00', '2005-01-01 07:00:00-05:00',
               '2005-01-01 08:00:00-05:00', '2005-01-01 09:00:00-05:00'],
              dtype='datetime64[ns, US/Eastern]', freq=None)

In [211]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1H', tz='Asia/Tashkent'))
data.tzinfo

<DstTzInfo 'Asia/Tashkent' LMT+4:37:00 STD>

In [216]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.union(data.append(pd.Index([1, 2, np.nan])))

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_6072\2768894436.py:2: RuntimeWarning: '<' not supported between instances of 'float' and 'Timestamp', sort order is undefined for incomparable objects.
  data.union(data.append(pd.Index([1, 2, np.nan])))


Index([2005-01-01 00:00:00, 2005-01-02 00:00:00, 2005-01-03 00:00:00,
       2005-01-04 00:00:00, 2005-01-05 00:00:00, 2005-01-06 00:00:00,
       2005-01-07 00:00:00, 2005-01-08 00:00:00, 2005-01-09 00:00:00,
       2005-01-10 00:00:00,                 1.0,                 2.0,
                       nan],
      dtype='object')

In [221]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.union_many.__doc__

'\n        A bit of a hack to accelerate unioning a collection of indexes.\n        '

In [231]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data

array([False, False, False, False, False, False, False, False, False,
       False])

In [237]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
print(data)
print(data.repeat(2).unique())

DatetimeIndex(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04',
               '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08',
               '2005-01-09', '2005-01-10'],
              dtype='datetime64[ns]', freq='D')
DatetimeIndex(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04',
               '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08',
               '2005-01-09', '2005-01-10'],
              dtype='datetime64[ns]', freq=None)


In [240]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D')).repeat(2)
data.value_counts()

2005-01-01    2
2005-01-02    2
2005-01-03    2
2005-01-04    2
2005-01-05    2
2005-01-06    2
2005-01-07    2
2005-01-08    2
2005-01-09    2
2005-01-10    2
dtype: int64

In [242]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.values

array(['2005-01-01T00:00:00.000000000', '2005-01-02T00:00:00.000000000',
       '2005-01-03T00:00:00.000000000', '2005-01-04T00:00:00.000000000',
       '2005-01-05T00:00:00.000000000', '2005-01-06T00:00:00.000000000',
       '2005-01-07T00:00:00.000000000', '2005-01-08T00:00:00.000000000',
       '2005-01-09T00:00:00.000000000', '2005-01-10T00:00:00.000000000'],
      dtype='datetime64[ns]')

In [247]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.view()

DatetimeIndex(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04',
               '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08',
               '2005-01-09', '2005-01-10'],
              dtype='datetime64[ns]', freq='D')

In [251]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.week

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_6072\4294732938.py:2: FutureWarning: weekofyear and week have been deprecated, please use DatetimeIndex.isocalendar().week instead, which returns a Series. To exactly reproduce the behavior of week and weekofyear and return an Index, you may call pd.Int64Index(idx.isocalendar().week)
  data.week


Int64Index([53, 53, 1, 1, 1, 1, 1, 1, 1, 2], dtype='int64')

In [253]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.weekday

Int64Index([5, 6, 0, 1, 2, 3, 4, 5, 6, 0], dtype='int64')

In [255]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.weekofyear

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_6072\1261852634.py:2: FutureWarning: weekofyear and week have been deprecated, please use DatetimeIndex.isocalendar().week instead, which returns a Series. To exactly reproduce the behavior of week and weekofyear and return an Index, you may call pd.Int64Index(idx.isocalendar().week)
  data.weekofyear


Int64Index([53, 53, 1, 1, 1, 1, 1, 1, 1, 2], dtype='int64')

In [263]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1D'))
data.where(data.shift(2))

DatetimeIndex(['2005-01-01', '2005-01-02', '2005-01-03', '2005-01-04',
               '2005-01-05', '2005-01-06', '2005-01-07', '2005-01-08',
               '2005-01-09', '2005-01-10'],
              dtype='datetime64[ns]', freq='D')

In [267]:
data = pd.DatetimeIndex(pd.date_range('1/1/2005', periods=10, freq='1Y'))
data.year

Int64Index([2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014], dtype='int64')

Thank you !