In [2]:
import pandas as pd

functions = [i for i in dir(pd.Categorical) if i[:1] != '_']

for i, v in enumerate(functions):
    print(i, v)

0 T
1 add_categories
2 argmax
3 argmin
4 argsort
5 as_ordered
6 as_unordered
7 astype
8 categories
9 check_for_ordered
10 codes
11 copy
12 delete
13 describe
14 dropna
15 dtype
16 equals
17 factorize
18 fillna
19 from_codes
20 insert
21 is_dtype_equal
22 isin
23 isna
24 isnull
25 map
26 max
27 memory_usage
28 min
29 mode
30 nbytes
31 ndim
32 notna
33 notnull
34 ordered
35 ravel
36 remove_categories
37 remove_unused_categories
38 rename_categories
39 reorder_categories
40 repeat
41 replace
42 reshape
43 searchsorted
44 set_categories
45 set_ordered
46 shape
47 shift
48 size
49 sort_values
50 swapaxes
51 take
52 take_nd
53 to_dense
54 to_list
55 to_numpy
56 tolist
57 transpose
58 unique
59 value_counts
60 view


In [39]:
x = pd.Categorical([1,2,3,4,1,3])
x

[1, 2, 3, 4, 1, 3]
Categories (4, int64): [1, 2, 3, 4]

In [17]:
x.T

[1, 2, 3, 4, 1, 3]
Categories (4, int64): [1, 2, 3, 4]

In [18]:
x.add_categories(5)

[1, 2, 3, 4, 1, 3]
Categories (5, int64): [1, 2, 3, 4, 5]

In [21]:
print(x)
x[x.argmax()]

[1, 2, 3, 4, 1, 3]
Categories (4, int64): [1, 2, 3, 4]


4

In [22]:
print(x)
x[x.argmin()]

[1, 2, 3, 4, 1, 3]
Categories (4, int64): [1, 2, 3, 4]


1

In [25]:
print(x)
x[x.argsort()]

[1, 2, 3, 4, 1, 3]
Categories (4, int64): [1, 2, 3, 4]


[1, 1, 2, 3, 3, 4]
Categories (4, int64): [1, 2, 3, 4]

In [44]:
print(x)
x.as_ordered

[1, 2, 3, 4, 1, 3]
Categories (4, int64): [1 < 2 < 3 < 4]


<bound method Categorical.as_ordered of [1, 2, 3, 4, 1, 3]
Categories (4, int64): [1 < 2 < 3 < 4]>

In [50]:
print(x)
x.as_unordered

[1, 2, 3, 4, 1, 3]
Categories (4, int64): [1, 2, 3, 4]


<bound method Categorical.as_unordered of [1, 2, 3, 4, 1, 3]
Categories (4, int64): [1, 2, 3, 4]>

In [58]:
import numpy as np
print(x)
x.astype(np.float64)

[1, 2, 3, 4, 1, 3]
Categories (4, int64): [1, 2, 3, 4]


array([1., 2., 3., 4., 1., 3.])

In [66]:
print(x)
x = x.add_categories(10)
x.categories

[1, 2, 3, 4, 1, 3]
Categories (4, int64): [1, 2, 3, 4]


Int64Index([1, 2, 3, 4, 10], dtype='int64')

In [68]:
print(x)
x.check_for_ordered

[1, 2, 3, 4, 1, 3]
Categories (5, int64): [1, 2, 3, 4, 10]


<bound method Categorical.check_for_ordered of [1, 2, 3, 4, 1, 3]
Categories (5, int64): [1, 2, 3, 4, 10]>

In [70]:
print(x)
x.codes

[1, 2, 3, 4, 1, 3]
Categories (5, int64): [1, 2, 3, 4, 10]


array([0, 1, 2, 3, 0, 2], dtype=int8)

In [88]:
print(x)
y = x.copy()
print(y)
y == x

[1, 2, 3, 4, 1, 3]
Categories (5, int64): [1, 2, 3, 4, 10]
[1, 2, 3, 4, 1, 3]
Categories (5, int64): [1, 2, 3, 4, 10]


array([ True,  True,  True,  True,  True,  True])

In [95]:
print(x)
x.delete([-1, 0, 1])

[1, 2, 3, 4, 1, 3]
Categories (5, int64): [1, 2, 3, 4, 10]


[3, 4, 1]
Categories (5, int64): [1, 2, 3, 4, 10]

In [97]:
print(x)
x.describe()

[1, 2, 3, 4, 1, 3]
Categories (5, int64): [1, 2, 3, 4, 10]


counts     freqs
categories                  
1                2  0.333333
2                1  0.166667
3                2  0.333333
4                1  0.166667
10               0  0.000000

In [102]:
x = pd.Categorical([1,2,3,1,2,np.nan])
print(x)
x.dropna

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


<bound method ExtensionArray.dropna of [1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]>

In [104]:
print(x)
x.dtype

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


CategoricalDtype(categories=[1, 2, 3], ordered=False)

In [107]:
print(x)
x.equals

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


<bound method Categorical.equals of [1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]>

In [109]:
print(x)
x.factorize()

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


(array([ 0,  1,  2,  0,  1, -1], dtype=int64),
 [1, 2, 3]
 Categories (3, int64): [1, 2, 3])

In [117]:
print(x)
x.fillna(1)

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


[1, 2, 3, 1, 2, 1]
Categories (3, int64): [1, 2, 3]

In [122]:
y = pd.Categorical.from_codes(codes=[0,1,0,1], dtype=pd.CategoricalDtype(['a', 'b'], ordered=True))
y

['a', 'b', 'a', 'b']
Categories (2, object): ['a' < 'b']

In [133]:
print(x)
x.insert(-1, item=None)

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


[1, 2, 3, 1, 2, NaN, NaN]
Categories (3, int64): [1, 2, 3]

In [136]:
print(x)
x.is_dtype_equal(y)


[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_2792\2693322613.py:2: FutureWarning: Categorical.is_dtype_equal is deprecated and will be removed in a future version
  x.is_dtype_equal(y)


False

In [138]:
print(x)
x.isin([1,2])

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


array([ True,  True, False,  True,  True, False])

In [140]:
print(x)
x.isna()

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


array([False, False, False, False, False,  True])

In [143]:
print(x)
x.isnull()

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


array([False, False, False, False, False,  True])

In [146]:
print(x)
def func(p):
    return p*10
x.map(func)

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


[10, 20, 30, 10, 20, NaN]
Categories (3, int64): [10, 20, 30]

In [151]:
print(x)
x.max

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


<bound method Categorical.max of [1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]>

In [154]:
print(x)
x.memory_usage()

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


138

In [158]:
print(x)
x.min

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


<bound method Categorical.min of [1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]>

In [161]:
print(x)
x.mode()


[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_2792\4161692488.py:2: FutureWarning: Categorical.mode is deprecated and will be removed in a future version. Use Series.mode instead.
  x.mode()


[1, 2]
Categories (3, int64): [1, 2, 3]

In [163]:
print(x)
x.nbytes

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


30

In [165]:
print(x)
x.ndim

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


1

In [167]:
print(x)
x.notna()

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


array([ True,  True,  True,  True,  True, False])

In [170]:
print(x)
x.notnull()

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


array([ True,  True,  True,  True,  True, False])

In [174]:
print(x)
x.ordered

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


False

In [180]:
print(x)
x.ravel('A')

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]

In [183]:
print(x)
x.remove_categories(1)

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


[NaN, 2, 3, NaN, 2, NaN]
Categories (2, int64): [2, 3]

In [188]:
print(x)
x.remove_unused_categories()

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]

In [192]:
print(x)
x.rename_categories([3,4,5])

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


[3, 4, 5, 3, 4, NaN]
Categories (3, int64): [3, 4, 5]

In [199]:
print(x)
x.reorder_categories

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


<bound method Categorical.reorder_categories of [1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]>

In [203]:
print(x)
x.repeat(3)

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


[1, 1, 1, 2, 2, ..., 2, 2, NaN, NaN, NaN]
Length: 18
Categories (3, int64): [1, 2, 3]

In [206]:
print(x)
x.replace(1, 100)

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_2792\3458565353.py:2: FutureWarning: In a future version of pandas all arguments of Categorical.replace except for the argument 'value' will be keyword-only.
  x.replace(1, 100)
C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_2792\3458565353.py:2: FutureWarning: Categorical.replace is deprecated and will be removed in a future version. Use Series.replace directly instead.
  x.replace(1, 100)


[100, 2, 3, 100, 2, NaN]
Categories (3, int64): [100, 2, 3]

In [223]:
print(x)
x.reshape(6)

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]

In [229]:
print(x)
x.searchsorted([1,2,3], side='right')

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


array([6, 6, 6], dtype=int64)

In [234]:
print(x)
x.set_categories([9,1,7])

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


[1, NaN, NaN, 1, NaN, NaN]
Categories (3, int64): [9, 1, 7]

In [240]:
print(x)
x.set_ordered(True)

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1 < 2 < 3]

In [242]:
print(x)
x.shape

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


(6,)

In [245]:
print(x)
x.shift(periods=2)

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


[NaN, NaN, 1, 2, 3, 1]
Categories (3, int64): [1, 2, 3]

In [247]:
print(x)
x.size

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


6

In [249]:
print(x)
x.sort_values()

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


[1, 1, 2, 2, 3, NaN]
Categories (3, int64): [1, 2, 3]

In [264]:
print(x)
x.swapaxes(0,-1)

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]

In [267]:
print(x)
x.take([0,1,-1])

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


[1, 2, NaN]
Categories (3, int64): [1, 2, 3]

In [270]:
print(x)
x.take_nd([0,1])

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_2792\3064203266.py:2: FutureWarning: Categorical.take_nd is deprecated, use Categorical.take instead
  x.take_nd([0,1])


[1, 2]
Categories (3, int64): [1, 2, 3]

In [273]:
print(x)
x.to_dense()

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_2792\2254180175.py:2: FutureWarning: Categorical.to_dense is deprecated and will be removed in a future version.  Use np.asarray(cat) instead.
  x.to_dense()


array([ 1.,  2.,  3.,  1.,  2., nan])

In [275]:
print(x)
x.to_list()

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


[1, 2, 3, 1, 2, nan]

In [278]:
print(x)
y = x.to_numpy()
print(y, y.dtype)

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]
[ 1.  2.  3.  1.  2. nan] float64


In [280]:
print(x)
x.tolist()

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


[1, 2, 3, 1, 2, nan]

In [285]:
print(x)
x.transpose()

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]

In [287]:
print(x)
x.unique()

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


[1, 2, 3, NaN]
Categories (3, int64): [1, 2, 3]

In [289]:
print(x)
x.value_counts()

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


1    2
2    2
3    1
dtype: int64

In [291]:
print(x)
x.view()

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]