In [1]:
import numpy as np

import pandas as pd

functions = [i for i in dir(pd.CategoricalIndex) if i[:1] != '_']

for i, v in enumerate(functions):
    print(i, v)

0 T
1 add_categories
2 all
3 any
4 append
5 argmax
6 argmin
7 argsort
8 array
9 as_ordered
10 as_unordered
11 asi8
12 asof
13 asof_locs
14 astype
15 categories
16 codes
17 copy
18 delete
19 difference
20 drop
21 drop_duplicates
22 droplevel
23 dropna
24 dtype
25 duplicated
26 empty
27 equals
28 factorize
29 fillna
30 format
31 get_indexer
32 get_indexer_for
33 get_indexer_non_unique
34 get_level_values
35 get_loc
36 get_slice_bound
37 get_value
38 groupby
39 has_duplicates
40 hasnans
41 holds_integer
42 identical
43 inferred_type
44 insert
45 intersection
46 is_
47 is_all_dates
48 is_boolean
49 is_categorical
50 is_dtype_equal
51 is_floating
52 is_integer
53 is_interval
54 is_mixed
55 is_monotonic
56 is_monotonic_decreasing
57 is_monotonic_increasing
58 is_numeric
59 is_object
60 is_type_compatible
61 is_unique
62 isin
63 isna
64 isnull
65 item
66 join
67 map
68 max
69 memory_usage
70 min
71 name
72 names
73 nbytes
74 ndim
75 nlevels
76 notna
77 notnull
78 nunique
79 ordered
80 putmask

In [3]:
x = pd.CategoricalIndex([1,2,3,1,2,4])
x

CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4], ordered=False, dtype='category')

In [4]:
print(x)
x.T

CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4], ordered=False, dtype='category')


CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4], ordered=False, dtype='category')

In [8]:
print(x)
x.add_categories([10])

CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4], ordered=False, dtype='category')


CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4, 10], ordered=False, dtype='category')

In [16]:
print(x)
x.all

CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4], ordered=False, dtype='category')


<bound method Index.all of CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4], ordered=False, dtype='category')>

In [19]:
print(x)
x.any

CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4], ordered=False, dtype='category')


<bound method Index.any of CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4], ordered=False, dtype='category')>

In [28]:
print(x)
x.append

CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4], ordered=False, dtype='category')


<bound method Index.append of CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4], ordered=False, dtype='category')>

In [32]:
print(x)
x[x.argmax()]

CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4], ordered=False, dtype='category')


4

In [34]:
print(x)
x[x.argmin()]

CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4], ordered=False, dtype='category')


1

In [37]:
print(x)
x[x.argsort()]

CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4], ordered=False, dtype='category')


CategoricalIndex([1, 1, 2, 2, 3, 4], categories=[1, 2, 3, 4], ordered=False, dtype='category')

In [39]:
print(x)
x.array

CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4], ordered=False, dtype='category')


[1, 2, 3, 1, 2, 4]
Categories (4, int64): [1, 2, 3, 4]

In [46]:
print(x)
x.as_ordered()

CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4], ordered=True, dtype='category')


CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4], ordered=True, dtype='category')

In [48]:
print(x)
x.as_unordered()

CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4], ordered=True, dtype='category')


CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4], ordered=False, dtype='category')

In [51]:
print(x)
x.asi8

CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4], ordered=True, dtype='category')


C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_808\3254979091.py:2: FutureWarning: Index.asi8 is deprecated and will be removed in a future version.
  x.asi8


In [56]:
idx = pd.Index(['2013-12-31', '2014-01-02', '2014-01-03'])
idx.asof('2014-01-01')

'2013-12-31'

In [69]:
idx = pd.Index(['2013-12-31', '2014-01-02', '2014-01-03'])
idx.asof_locs.__doc__

'\n        Return the locations (indices) of labels in the index.\n\n        As in the `asof` function, if the label (a particular entry in\n        `where`) is not in the index, the latest index label up to the\n        passed label is chosen and its index returned.\n\n        If all of the labels in the index are later than a label in `where`,\n        -1 is returned.\n\n        `mask` is used to ignore NA values in the index during calculation.\n\n        Parameters\n        ----------\n        where : Index\n            An Index consisting of an array of timestamps.\n        mask : np.ndarray[bool]\n            Array of booleans denoting where values in the original\n            data are not NA.\n\n        Returns\n        -------\n        np.ndarray[np.intp]\n            An array of locations (indices) of the labels from the Index\n            which correspond to the return values of the `asof` function\n            for every element in `where`.\n        '

In [73]:
import numpy as np
print(x)
x.astype(np.float64)

CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4], ordered=True, dtype='category')


Float64Index([1.0, 2.0, 3.0, 1.0, 2.0, 4.0], dtype='float64')

In [76]:
print(x)
x.categories

CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4], ordered=True, dtype='category')


Int64Index([1, 2, 3, 4], dtype='int64')

In [78]:
print(x)
x.codes

CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4], ordered=True, dtype='category')


array([0, 1, 2, 0, 1, 3], dtype=int8)

In [85]:
print(x)
y = x.copy()
print(y)
y == x

CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4], ordered=True, dtype='category')
CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4], ordered=True, dtype='category')


array([ True,  True,  True,  True,  True,  True])

In [88]:
print(x)
x.delete([-1,0,1])

CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4], ordered=True, dtype='category')


CategoricalIndex([3, 1, 2], categories=[1, 2, 3, 4], ordered=True, dtype='category')

In [91]:
print(x)
x.difference([1,2,3])

CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4], ordered=True, dtype='category')


CategoricalIndex([4], categories=[1, 2, 3, 4], ordered=True, dtype='category')

In [108]:
print(x)
x.drop(labels=[1])

CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4], ordered=True, dtype='category')


CategoricalIndex([2, 3, 2, 4], categories=[1, 2, 3, 4], ordered=True, dtype='category')

In [111]:
print(x)
x.drop_duplicates()

CategoricalIndex([1, 2, 3, 1, 2, 4], categories=[1, 2, 3, 4], ordered=True, dtype='category')


CategoricalIndex([1, 2, 3, 4], categories=[1, 2, 3, 4], ordered=True, dtype='category')

In [120]:
mi = pd.MultiIndex.from_arrays([[1, 2], [3, 4], [5, 6]], names=['x', 'y', 'z'])
print(mi)
mi.droplevel()

MultiIndex([(1, 3, 5),
            (2, 4, 6)],
           names=['x', 'y', 'z'])


MultiIndex([(3, 5),
            (4, 6)],
           names=['y', 'z'])

In [123]:
x = pd.CategoricalIndex([1,2,3,1,2,np.nan])
print(x)
x.dropna()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


CategoricalIndex([1, 2, 3, 1, 2], categories=[1, 2, 3], ordered=False, dtype='category')

In [125]:
print(x)
x.dtype

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


CategoricalDtype(categories=[1, 2, 3], ordered=False)

In [128]:
print(x)
x.duplicated('first')

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


array([False, False, False,  True,  True, False])

In [130]:
print(x)
x.empty

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


False

In [138]:
print(x)
y = pd.CategoricalIndex([1,2,3,5])
x.equals(y)

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


False

In [141]:
print(x)
x.factorize()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


(array([ 0,  1,  2,  0,  1, -1], dtype=int64),
 CategoricalIndex([1, 2, 3], categories=[1, 2, 3], ordered=False, dtype='category'))

In [148]:
print(x)
x.fillna(100)

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


Float64Index([1.0, 2.0, 3.0, 1.0, 2.0, 100.0], dtype='float64')

In [150]:
print(x)
x.format()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


['1', '2', '3', '1', '2', 'NaN']

In [175]:
print(x)
x.get_indexer.__doc__

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


"\nCompute indexer and mask for new index given the current index.\n\nThe indexer should be then used as an input to ndarray.take to align the\ncurrent data to the new index.\n\nParameters\n----------\ntarget : Index\nmethod : {None, 'pad'/'ffill', 'backfill'/'bfill', 'nearest'}, optional\n    * default: exact matches only.\n    * pad / ffill: find the PREVIOUS index value if no exact match.\n    * backfill / bfill: use NEXT index value if no exact match\n    * nearest: use the NEAREST index value if no exact match. Tied\n      distances are broken by preferring the larger index value.\nlimit : int, optional\n    Maximum number of consecutive labels in ``target`` to match for\n    inexact matches.\ntolerance : optional\n    Maximum distance between original and new labels for inexact\n    matches. The values of the index at the matching locations must\n    satisfy the equation ``abs(index[indexer] - target) <= tolerance``.\n\n    Tolerance may be a scalar value, which applies the same 

In [163]:
print(x)
x.get_indexer_for([np.nan])

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


array([5], dtype=int64)

In [170]:
print(x)
x.get_indexer_non_unique(pd.Index([1]))

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


(array([0, 3], dtype=int64), array([], dtype=int64))

In [184]:
print(x)
x.get_level_values(0)

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')

In [186]:
print(x)
x.get_loc(1)

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


array([ True, False, False,  True, False, False])

In [197]:
print(x)
x.get_slice_bound(side='left', label=None)

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


5

In [212]:
print(x)
x.get_value.__doc__

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


"\n        Fast lookup of value from 1-dimensional ndarray.\n\n        Only use this if you know what you're doing.\n\n        Returns\n        -------\n        scalar or Series\n        "

In [223]:
a = pd.DataFrame({'a': [1], 'b': [2]})
a.groupby('a').describe()

b                                  
  count mean std  min  25%  50%  75%  max
a                                        
1   1.0  2.0 NaN  2.0  2.0  2.0  2.0  2.0

In [225]:
print(x)
x.has_duplicates

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


True

In [227]:
print(x)
x.hasnans

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


True

In [229]:
print(x)
x.holds_integer()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


False

In [235]:
print(x)
x.identical(1)

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


False

In [237]:
print(x)
x.inferred_type

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


'categorical'

In [240]:
print(x)
x.insert(-1, 10)

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


Float64Index([1.0, 2.0, 3.0, 1.0, 2.0, 10.0, nan], dtype='float64')

In [243]:
print(x)
x.intersection([9,8,7,6,5,3])

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


Float64Index([3.0], dtype='float64')

In [249]:
print(x)
x.is_(np.nan)

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


False

In [251]:
print(x)
x.is_all_dates

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


False

In [253]:
print(x)
x.is_boolean()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


False

In [255]:
print(x)
x.is_categorical()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


True

In [259]:
print(x)
x.is_dtype_equal(np.int64)

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_808\191053426.py:2: FutureWarning: Categorical.is_dtype_equal is deprecated and will be removed in a future version
  x.is_dtype_equal(np.int64)


False

In [261]:
print(x)
x.is_floating()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


False

In [263]:
print(x)
x.is_integer()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


False

In [264]:
print(x)
x.is_interval()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


False

In [266]:
print(x)
x.is_mixed()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_808\3281929459.py:2: FutureWarning: Index.is_mixed is deprecated and will be removed in a future version. Check index.inferred_type directly instead.
  x.is_mixed()


False

In [268]:
print(x)
x.is_monotonic

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_808\3976452832.py:2: FutureWarning: is_monotonic is deprecated and will be removed in a future version. Use is_monotonic_increasing instead.
  x.is_monotonic


False

In [270]:
print(x)
x.is_monotonic_decreasing

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


False

In [272]:
print(x)
x.is_monotonic_increasing

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


False

In [274]:
print(x)
x.is_numeric()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


False

In [276]:
print(x)
x.is_object()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


False

In [280]:
print(x)
x.is_type_compatible(None)

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_808\1936553790.py:2: FutureWarning: Index.is_type_compatible is deprecated and will be removed in a future version.
  x.is_type_compatible(None)


False

In [282]:
print(x)
x.is_unique

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


False

In [286]:
print(x)
x.isin([np.nan])

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


array([False, False, False, False, False,  True])

In [288]:
print(x)
x.isna()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


array([False, False, False, False, False,  True])

In [291]:
print(x)
x.isnull()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


array([False, False, False, False, False,  True])

In [294]:
print(x)
x.item.__doc__

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


'\n        Return the first element of the underlying data as a Python scalar.\n\n        Returns\n        -------\n        scalar\n            The first element of %(klass)s.\n\n        Raises\n        ------\n        ValueError\n            If the data is not length-1.\n        '

In [306]:
print(x)
x.join([0])

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


Float64Index([1.0, 1.0, 2.0, 2.0, 3.0, nan], dtype='float64')

In [313]:
print(x)
def new_f(p):
    return p*10
x.map(new_f)

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


CategoricalIndex([10, 20, 30, 10, 20, nan], categories=[10, 20, 30], ordered=False, dtype='category')

In [320]:
print(x)
x.max

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


<bound method _inherit_from_data.<locals>.method of CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')>

In [323]:
print(x)
x.memory_usage()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


254

In [330]:
print(x)
x.min

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


<bound method _inherit_from_data.<locals>.method of CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')>

In [336]:
print(x)
x.name

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


In [338]:
print(x)
x.names

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


FrozenList([None])

In [340]:
print(x)
x.nbytes

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


30

In [342]:
print(x)
x.ndim

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


1

In [344]:
print(x)
x.nlevels

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


1

In [346]:
print(x)
x.notna()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


array([ True,  True,  True,  True,  True, False])

In [349]:
print(x)
x.notnull()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


array([ True,  True,  True,  True,  True, False])

In [350]:
print(x)
x.nunique()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


3

In [352]:
print(x)
x.ordered

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


False

In [359]:
print(x)
x.putmask(['a', 'b', 'c', 's', 'd', 'g'], [1,2,3,1,2,np.nan])

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')
CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


In [361]:
print(x)
x.ravel()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_808\87049756.py:2: FutureWarning: Index.ravel returning ndarray is deprecated; in a future version this will return a view on self.
  x.ravel()


array([ 0,  1,  2,  0,  1, -1], dtype=int8)

In [365]:
print(x)
x.reindex(target=pd.Index([9]))

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_808\3305880912.py:2: FutureWarning: reindexing with a non-unique Index is deprecated and will raise in a future version.
  x.reindex(target=pd.Index([9]))


(Float64Index([nan], dtype='float64'), array([5], dtype=int64))

In [373]:
print(x)
x.remove_categories([1,2])

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


CategoricalIndex([nan, nan, 3, nan, nan, nan], categories=[3], ordered=False, dtype='category')

In [377]:
print(x)
x.remove_unused_categories()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')

In [381]:
print(x)
x.rename("iqrorjoncoder")

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category', name='iqrorjoncoder')

In [393]:
print(x)
def new_f(p):
    return p*100
x.rename_categories(new_f)

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


CategoricalIndex([100, 200, 300, 100, 200, nan], categories=[100, 200, 300], ordered=False, dtype='category')

In [401]:
print(x)
x.reorder_categories.__doc__

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


'\n        Reorder categories as specified in new_categories.\n\n        `new_categories` need to include all old categories and no new category\n        items.\n\n        Parameters\n        ----------\n        new_categories : Index-like\n           The categories in new order.\n        ordered : bool, optional\n           Whether or not the categorical is treated as a ordered categorical.\n           If not given, do not change the ordered information.\n        inplace : bool, default False\n           Whether or not to reorder the categories inplace or return a copy of\n           this categorical with reordered categories.\n\n           .. deprecated:: 1.3.0\n\n        Returns\n        -------\n        cat : Categorical or None\n            Categorical with removed categories or None if ``inplace=True``.\n\n        Raises\n        ------\n        ValueError\n            If the new categories do not contain all old category items or any\n            new ones\n\n        See Also\n  

In [403]:
print(x)
x.repeat(2)

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


CategoricalIndex([1, 1, 2, 2, 3, 3, 1, 1, 2, 2, nan, nan], categories=[1, 2, 3], ordered=False, dtype='category')

In [411]:
print(x)
x.searchsorted([1])

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


array([0], dtype=int64)

In [417]:
print(x)
x.set_categories([1])

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


CategoricalIndex([1, nan, nan, 1, nan, nan], categories=[1], ordered=False, dtype='category')

In [419]:
print(x)
x.set_names("iqrorjon")

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category', name='iqrorjon')

In [426]:
print(x)
x.set_value.__doc__

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


"\n        Fast lookup of value from 1-dimensional ndarray.\n\n        .. deprecated:: 1.0\n\n        Notes\n        -----\n        Only use this if you know what you're doing.\n        "

In [428]:
print(x)
x.shape

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


(6,)

In [434]:
xxx = pd.Categorical([1,2,3,1,2,np.nan])
print(xxx)
xxx.shift(periods=2)

[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]


[NaN, NaN, 1, 2, 3, 1]
Categories (3, int64): [1, 2, 3]

In [436]:
print(x)
x.size

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


6

In [438]:
print(x)
x.slice_indexer()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


slice(0, 6, None)

In [440]:
print(x)
x.slice_locs()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


(0, 6)

In [443]:
print(x)
# x.sort()
x.sort_values()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


CategoricalIndex([1, 1, 2, 2, 3, nan], categories=[1, 2, 3], ordered=False, dtype='category')

In [445]:
print(x)
x.sortlevel()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


(CategoricalIndex([1, 1, 2, 2, 3, nan], categories=[1, 2, 3], ordered=False, dtype='category'),
 array([0, 3, 1, 4, 2, 5], dtype=int64))

In [452]:
print(x)
y = pd.CategoricalIndex([1,2,3,1,3,4])
print(y)
x.symmetric_difference(y)

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')
CategoricalIndex([1, 2, 3, 1, 3, 4], categories=[1, 2, 3, 4], ordered=False, dtype='category')


Float64Index([4.0, nan], dtype='float64')

In [456]:
print(x)
x.take([1])

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


CategoricalIndex([2], categories=[1, 2, 3], ordered=False, dtype='category')

In [460]:
print(x)
x.take_nd([2])

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_808\4240524533.py:2: FutureWarning: CategoricalIndex.take_nd is deprecated, use CategoricalIndex.take instead.
  x.take_nd([2])


CategoricalIndex([3], categories=[1, 2, 3], ordered=False, dtype='category')

In [462]:
print(x)
x.to_flat_index()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')

In [464]:
print(x)
x.to_frame()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


0
1      1
2      2
3      3
1      1
2      2
NaN  NaN

In [467]:
print(x)
x.to_list()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


[1, 2, 3, 1, 2, nan]

In [469]:
print(x)
x.to_native_types()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_808\597243550.py:2: FutureWarning: The 'to_native_types' method is deprecated and will be removed in a future version. Use 'astype(str)' instead.
  x.to_native_types()


array(['1.0', '2.0', '3.0', '1.0', '2.0', ''], dtype='<U32')

In [471]:
print(x)
x.to_numpy()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


array([ 1.,  2.,  3.,  1.,  2., nan])

In [473]:
print(x)
x.to_series()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


1        1
2        2
3        3
1        1
2        2
NaN    NaN
dtype: category
Categories (3, int64): [1, 2, 3]

In [474]:
print(x)
x.tolist()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


[1, 2, 3, 1, 2, nan]

In [477]:
print(x)
x.transpose()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')

In [481]:
print(x)
y = pd.CategoricalIndex([1,2,3,1,3,4])
print(y)
x.union(y)

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')
CategoricalIndex([1, 2, 3, 1, 3, 4], categories=[1, 2, 3, 4], ordered=False, dtype='category')


Float64Index([1.0, 1.0, 2.0, 2.0, 3.0, 3.0, 4.0, nan], dtype='float64')

In [483]:
print(x)
x.unique()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


CategoricalIndex([1, 2, 3, nan], categories=[1, 2, 3], ordered=False, dtype='category')

In [485]:
print(x)
x.value_counts()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


1    2
2    2
3    1
dtype: int64

In [487]:
print(x)
x.values

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


[1, 2, 3, 1, 2, NaN]
Categories (3, int64): [1, 2, 3]

In [489]:
print(x)
x.view()

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')

In [490]:
print(x)
x.where(x == 2)

CategoricalIndex([1, 2, 3, 1, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')


CategoricalIndex([nan, 2, nan, nan, 2, nan], categories=[1, 2, 3], ordered=False, dtype='category')