In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

functions = [i for i in dir(pd.Float64Index) if i[:1] != '_']

for i, v in enumerate(functions):
    print(i, v)

0 T
1 all
2 any
3 append
4 argmax
5 argmin
6 argsort
7 array
8 asi8
9 asof
10 asof_locs
11 astype
12 copy
13 delete
14 difference
15 drop
16 drop_duplicates
17 droplevel
18 dropna
19 dtype
20 duplicated
21 empty
22 equals
23 factorize
24 fillna
25 format
26 get_indexer
27 get_indexer_for
28 get_indexer_non_unique
29 get_level_values
30 get_loc
31 get_slice_bound
32 get_value
33 groupby
34 has_duplicates
35 hasnans
36 holds_integer
37 identical
38 inferred_type
39 insert
40 intersection
41 is_
42 is_all_dates
43 is_boolean
44 is_categorical
45 is_floating
46 is_integer
47 is_interval
48 is_mixed
49 is_monotonic
50 is_monotonic_decreasing
51 is_monotonic_increasing
52 is_numeric
53 is_object
54 is_type_compatible
55 is_unique
56 isin
57 isna
58 isnull
59 item
60 join
61 map
62 max
63 memory_usage
64 min
65 name
66 names
67 nbytes
68 ndim
69 nlevels
70 notna
71 notnull
72 nunique
73 putmask
74 ravel
75 reindex
76 rename
77 repeat
78 searchsorted
79 set_names
80 set_value
81 shape
82 shift

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1585188748.py:5: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  functions = [i for i in dir(pd.Float64Index) if i[:1] != '_']


In [33]:
data = pd.Float64Index([1,2,3,4])
data.T

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\2501042142.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


Float64Index([1.0, 2.0, 3.0, 4.0], dtype='float64')

In [40]:
data = pd.Float64Index([1,2,3,4])
data.all

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\2546132042.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


<bound method Index.all of Float64Index([1.0, 2.0, 3.0, 4.0], dtype='float64')>

In [41]:
data = pd.Float64Index([1,2,3,4])
data.any

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1704341632.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


<bound method Index.any of Float64Index([1.0, 2.0, 3.0, 4.0], dtype='float64')>

In [43]:
data = pd.Float64Index([1,2,3,4])
data.append(pd.Index([1,2,3]))

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\2987917164.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


Float64Index([1.0, 2.0, 3.0, 4.0, 1.0, 2.0, 3.0], dtype='float64')

In [46]:
data = pd.Float64Index([1,2,3,4])
data[data.argmax()]

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1196728404.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


4.0

In [47]:
data = pd.Float64Index([1,2,3,4])
data[data.argmin()]

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\4273293600.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


1.0

In [51]:
data = pd.Float64Index([10,12,1,2,3,4])
data[data.argsort()]

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3919494131.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([10,12,1,2,3,4])


Float64Index([1.0, 2.0, 3.0, 4.0, 10.0, 12.0], dtype='float64')

In [55]:
data = pd.Float64Index([1,2,3,4])
data.array

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3507632520.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


<PandasArray>
[1.0, 2.0, 3.0, 4.0]
Length: 4, dtype: float64

In [60]:
data = pd.Float64Index([1,2,3,4])
data.asi8

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3158714467.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])
C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3158714467.py:2: FutureWarning: Index.asi8 is deprecated and will be removed in a future version.
  data.asi8


In [70]:
data = pd.Float64Index([1,2,3,4])
print(data.asof(5))
print(data.asof(4))
print(data.asof(3))

4.0
4.0
3.0


C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\840341096.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


In [90]:
data = pd.Float64Index([1,2,3,4])
data.asof_locs.__doc__

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1841333773.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


'\n        Return the locations (indices) of labels in the index.\n\n        As in the `asof` function, if the label (a particular entry in\n        `where`) is not in the index, the latest index label up to the\n        passed label is chosen and its index returned.\n\n        If all of the labels in the index are later than a label in `where`,\n        -1 is returned.\n\n        `mask` is used to ignore NA values in the index during calculation.\n\n        Parameters\n        ----------\n        where : Index\n            An Index consisting of an array of timestamps.\n        mask : np.ndarray[bool]\n            Array of booleans denoting where values in the original\n            data are not NA.\n\n        Returns\n        -------\n        np.ndarray[np.intp]\n            An array of locations (indices) of the labels from the Index\n            which correspond to the return values of the `asof` function\n            for every element in `where`.\n        '

In [93]:
data = pd.Float64Index([1,2,3,4])
data.astype(np.int64)

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3423273408.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


Int64Index([1, 2, 3, 4], dtype='int64')

In [100]:
data = pd.Float64Index([1,2,3,4])
print(data.copy() == data)
print(data.copy() is data)

[ True  True  True  True]
False


C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3304237561.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


In [103]:
data = pd.Float64Index([1,2,3,4])
data.delete([1,-1,0])

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\4282038518.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


Float64Index([3.0], dtype='float64')

In [109]:
data = pd.Float64Index([1,2,3,4])
data.difference(data.copy())

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\953057918.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


Float64Index([], dtype='float64')

In [111]:
data = pd.Float64Index([1,2,3,4])
data.drop(1)

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\678219585.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


Float64Index([2.0, 3.0, 4.0], dtype='float64')

In [113]:
data = pd.Float64Index([1,2,3,4,1,2,3])
data.drop_duplicates()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\2260352990.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4,1,2,3])


Float64Index([1.0, 2.0, 3.0, 4.0], dtype='float64')

In [124]:
data = pd.Float64Index([1,2,3,4])
data.droplevel.__doc__

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3739935268.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


"\n        Return index with requested level(s) removed.\n\n        If resulting index has only 1 level left, the result will be\n        of Index type, not MultiIndex.\n\n        Parameters\n        ----------\n        level : int, str, or list-like, default 0\n            If a string is given, must be the name of a level\n            If list-like, elements must be names or indexes of levels.\n\n        Returns\n        -------\n        Index or MultiIndex\n\n        Examples\n        --------\n        >>> mi = pd.MultiIndex.from_arrays(\n        ... [[1, 2], [3, 4], [5, 6]], names=['x', 'y', 'z'])\n        >>> mi\n        MultiIndex([(1, 3, 5),\n                    (2, 4, 6)],\n                   names=['x', 'y', 'z'])\n\n        >>> mi.droplevel()\n        MultiIndex([(3, 5),\n                    (4, 6)],\n                   names=['y', 'z'])\n\n        >>> mi.droplevel(2)\n        MultiIndex([(1, 3),\n                    (2, 4)],\n                   names=['x', 'y'])\n\n        >>>

In [126]:
data = pd.Float64Index([1,2,3,4,np.nan, np.nan])
data.dropna()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1845660908.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4,np.nan, np.nan])


Float64Index([1.0, 2.0, 3.0, 4.0], dtype='float64')

In [145]:
data = pd.Float64Index([1,2,3,4])
data.dtype

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\2479479653.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


dtype('float64')

In [149]:
data = pd.Float64Index([1,1,2,3,4])
data.duplicated()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\104087242.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,1,2,3,4])


array([False,  True, False, False, False])

In [157]:
data = pd.Float64Index([1,2,3,4])
data.empty

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\558488564.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


False

In [158]:
data = pd.Float64Index([1,2,3,4])
data.equals

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3380714326.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


<bound method Index.equals of Float64Index([1.0, 2.0, 3.0, 4.0], dtype='float64')>

In [160]:
data = pd.Float64Index([1,2,3,4])
data.factorize()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3109501084.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


(array([0, 1, 2, 3], dtype=int64),
 Float64Index([1.0, 2.0, 3.0, 4.0], dtype='float64'))

In [170]:
data = pd.Float64Index([1,2,3,4,np.nan, np.nan])
data.fillna(1000)

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3436270363.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4,np.nan, np.nan])


Float64Index([1.0, 2.0, 3.0, 4.0, 1000.0, 1000.0], dtype='float64')

In [173]:
data = pd.Float64Index([1,2,3,4])
data.format()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3320394620.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


['1.0', '2.0', '3.0', '4.0']

In [181]:
data = pd.Float64Index([1,2,3,4])
data.get_indexer

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\2867755289.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


<bound method Index.get_indexer of Float64Index([1.0, 2.0, 3.0, 4.0], dtype='float64')>

In [185]:
data = pd.Float64Index([1,2,3,4])
data.get_indexer_for

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1871372919.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


<bound method Index.get_indexer_for of Float64Index([1.0, 2.0, 3.0, 4.0], dtype='float64')>

In [187]:
data = pd.Float64Index([1,2,3,4])
data.get_indexer_non_unique

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3906139655.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


<bound method Index.get_indexer_non_unique of Float64Index([1.0, 2.0, 3.0, 4.0], dtype='float64')>

In [191]:
data = pd.Float64Index([1,2,3,4])
data.get_level_values

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1096008746.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


<bound method Index._get_level_values of Float64Index([1.0, 2.0, 3.0, 4.0], dtype='float64')>

In [195]:
data = pd.Float64Index([1,2,3,4])
data.get_loc

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3980837881.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


<bound method Index.get_loc of Float64Index([1.0, 2.0, 3.0, 4.0], dtype='float64')>

In [200]:
data = pd.Float64Index([1,2,3,4])
data.get_slice_bound.__doc__

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3148375980.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


"\n        Calculate slice bound that corresponds to given label.\n\n        Returns leftmost (one-past-the-rightmost if ``side=='right'``) position\n        of given label.\n\n        Parameters\n        ----------\n        label : object\n        side : {'left', 'right'}\n        kind : {'loc', 'getitem'} or None\n\n            .. deprecated:: 1.4.0\n\n        Returns\n        -------\n        int\n            Index of label.\n        "

In [209]:
data = pd.Float64Index([1,2,3,4])
data.get_value.__doc__

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3519329389.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


"\n        Fast lookup of value from 1-dimensional ndarray.\n\n        Only use this if you know what you're doing.\n\n        Returns\n        -------\n        scalar or Series\n        "

In [216]:
data = pd.Float64Index([1,2,3,4])
data.groupby(values=[100,200])

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1870570277.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


{100: [1.0], 200: [2.0]}

In [220]:
data = pd.Float64Index([1,2,3,4])
data.has_duplicates

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\2936024221.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


False

In [222]:
data = pd.Float64Index([1,2,3,4, np.nan])
data.hasnans

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1691806041.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4, np.nan])


True

In [225]:
data = pd.Float64Index([1,2,3,4])
data.holds_integer()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\443691762.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


False

In [248]:
data = pd.Float64Index([1,2,3,4])
data.identical(data.copy())

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3420452926.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


True

In [251]:
data = pd.Float64Index([1,2,3,4])
data.inferred_type

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\911086164.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


'floating'

In [257]:
data = pd.Float64Index([1,2,3,4])
data.insert(item=[200,100], loc=[0,1])

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\2132730395.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


Float64Index([200.0, 1.0, 100.0, 2.0, 3.0, 4.0], dtype='float64')

In [265]:
data = pd.Float64Index([1,2,3,4])
data.intersection(data.insert(item=[100], loc=[1]))

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\4182904048.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


Float64Index([1.0, 2.0, 3.0, 4.0], dtype='float64')

In [269]:
data = pd.Float64Index([1,2,3,4])
data.is_(data)

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\804719060.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


True

In [273]:
data = pd.Float64Index([1,2,3,4])
data.is_all_dates

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\2203621129.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])
C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\2203621129.py:2: FutureWarning: Index.is_all_dates is deprecated, will be removed in a future version. check index.inferred_type instead.
  data.is_all_dates


False

In [276]:
data = pd.Float64Index([1,2,3,4, True])
data.is_boolean()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\9509436.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4, True])


False

In [280]:
data = pd.Float64Index([1,2,3,4])
data.is_categorical()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1116563416.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


False

In [282]:
data = pd.Float64Index([1,2,3,4])
data.is_floating()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3734045820.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


True

In [284]:
data = pd.Float64Index([1,2,3,4])
data.is_integer()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3827211226.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


False

In [286]:
data = pd.Float64Index([1,2,3,4])
data.is_interval()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3099659121.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


False

In [289]:
data = pd.Float64Index([1,2,3,4])
data.is_mixed()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1467081046.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])
C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1467081046.py:2: FutureWarning: Index.is_mixed is deprecated and will be removed in a future version. Check index.inferred_type directly instead.
  data.is_mixed()


False

In [293]:
data = pd.Float64Index([1,2,3,4])
data.is_monotonic

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\2733759573.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])
C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\2733759573.py:2: FutureWarning: is_monotonic is deprecated and will be removed in a future version. Use is_monotonic_increasing instead.
  data.is_monotonic


True

In [295]:
data = pd.Float64Index([1,2,3,4])
data.is_monotonic_decreasing

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\2658978187.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


False

In [296]:
data = pd.Float64Index([1,2,3,4])
data.is_monotonic_increasing

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1660759462.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


True

In [320]:
data = pd.Float64Index([1,2,3,4])
data.is_numeric()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3274451347.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


True

In [323]:
data = pd.Float64Index([1,2,3,4])
data.is_object()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1798633381.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


False

In [327]:
data = pd.Float64Index([1,2,3,4])
data.is_type_compatible(data.copy())

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\895482558.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])
C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\895482558.py:2: FutureWarning: Index.is_type_compatible is deprecated and will be removed in a future version.
  data.is_type_compatible(data.copy())


array([False, False, False, False])

In [331]:
data = pd.Float64Index([1,2,3,4])
data.is_unique

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1224722156.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


True

In [335]:
data = pd.Float64Index([1,2,3,4])
data.isin([1,2])

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1328147412.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


array([ True,  True, False, False])

In [338]:
data = pd.Float64Index([1,2,3,4,np.nan])
data.isna()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3729063831.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4,np.nan])


array([False, False, False, False,  True])

In [342]:
data = pd.Float64Index([1,2,3,4,np.nan])
data.isnull()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3133705779.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4,np.nan])


array([False, False, False, False,  True])

In [350]:
data = pd.Float64Index([1,2,3,4])
data.item.__doc__

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\2035821869.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


'\n        Return the first element of the underlying data as a Python scalar.\n\n        Returns\n        -------\n        scalar\n            The first element of %(klass)s.\n\n        Raises\n        ------\n        ValueError\n            If the data is not length-1.\n        '

In [354]:
data = pd.Float64Index([1,2,3,4])
data.join(data.copy())

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3160847061.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


Float64Index([1.0, 2.0, 3.0, 4.0], dtype='float64')

In [359]:
data = pd.Float64Index([1,2,3,4])
data.map.__doc__

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\196097758.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


"\n        Map values using an input mapping or function.\n\n        Parameters\n        ----------\n        mapper : function, dict, or Series\n            Mapping correspondence.\n        na_action : {None, 'ignore'}\n            If 'ignore', propagate NA values, without passing them to the\n            mapping correspondence.\n\n        Returns\n        -------\n        applied : Union[Index, MultiIndex], inferred\n            The output of the mapping function applied to the index.\n            If the function returns a tuple with more than one element\n            a MultiIndex will be returned.\n        "

In [361]:
data = pd.Float64Index([1,2,3,4])
data.max()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1545927332.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


4.0

In [364]:
data = pd.Float64Index([1,2,3,4])
data.memory_usage()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\2569826964.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


32

In [367]:
data = pd.Float64Index([1,2,3,4])
data.min()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1646593652.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


1.0

In [371]:
data = pd.Float64Index([1,2,3,4])
data.name

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3267290616.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


In [373]:
data = pd.Float64Index([1,2,3,4])
data.names

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1547497068.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


FrozenList([None])

In [375]:
data = pd.Float64Index([1,2,3,4])
data.nbytes

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1420113088.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


32

In [377]:
data = pd.Float64Index([1,2,3,4])
data.ndim

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\4249340297.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


1

In [379]:
data = pd.Float64Index([1,2,3,4])
data.nlevels

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\2192072891.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


1

In [383]:
data = pd.Float64Index([1,2,3,4,np.nan])
data.notna()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1186170483.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4,np.nan])


array([ True,  True,  True,  True, False])

In [387]:
data = pd.Float64Index([np.nan,1,2,3,4])
data.notnull()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\897724771.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([np.nan,1,2,3,4])


array([False,  True,  True,  True,  True])

In [389]:
data = pd.Float64Index([np.nan,1,2,3,4])
data.nunique()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1936185667.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([np.nan,1,2,3,4])


4

In [425]:
data = pd.Float64Index([1,2,3,4])
data.putmask(mask=[0,1,2,3], value=[1,2])

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\2603232188.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


Float64Index([1.0, 2.0, 1.0, 2.0], dtype='float64')

In [429]:
data = pd.Float64Index([1,2,3,4])
data.ravel()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\2826474325.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])
C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\2826474325.py:2: FutureWarning: Index.ravel returning ndarray is deprecated; in a future version this will return a view on self.
  data.ravel()


array([1., 2., 3., 4.])

In [433]:
data = pd.Float64Index([1,2,3,4]).to_series()
data.reindex()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\2503551554.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4]).to_series()


1.0    1.0
2.0    2.0
3.0    3.0
4.0    4.0
dtype: float64

In [436]:
data = pd.Float64Index([1,2,3,4])
data.rename("@iqrorjoncoder")

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\691575693.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


Float64Index([1.0, 2.0, 3.0, 4.0], dtype='float64', name='@iqrorjoncoder')

In [438]:
data = pd.Float64Index([1,2,3,4])
data.repeat(2)

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3825797040.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


Float64Index([1.0, 1.0, 2.0, 2.0, 3.0, 3.0, 4.0, 4.0], dtype='float64')

In [444]:
data = pd.Float64Index([1,2,3,4])
data.searchsorted(value=[4,2,1])

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\320066459.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


array([3, 1, 0], dtype=int64)

In [449]:
data = pd.Float64Index([1,2,3,4])
data.set_names("@iqrorjoncoder")

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3461948473.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


Float64Index([1.0, 2.0, 3.0, 4.0], dtype='float64', name='@iqrorjoncoder')

In [465]:
data = pd.Float64Index([1,2,3,4])
data.set_value.__doc__

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1936924947.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


"\n        Fast lookup of value from 1-dimensional ndarray.\n\n        .. deprecated:: 1.0\n\n        Notes\n        -----\n        Only use this if you know what you're doing.\n        "

In [467]:
data = pd.Float64Index([1,2,3,4])
data.shape

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1526025645.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


(4,)

In [478]:
data = pd.Float64Index([1,2,23])
data.shift.__doc__

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\850290347.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,23])


"\n        Shift index by desired number of time frequency increments.\n\n        This method is for shifting the values of datetime-like indexes\n        by a specified time increment a given number of times.\n\n        Parameters\n        ----------\n        periods : int, default 1\n            Number of periods (or increments) to shift by,\n            can be positive or negative.\n        freq : pandas.DateOffset, pandas.Timedelta or str, optional\n            Frequency increment to shift by.\n            If None, the index is shifted by its own `freq` attribute.\n            Offset aliases are valid strings, e.g., 'D', 'W', 'M' etc.\n\n        Returns\n        -------\n        pandas.Index\n            Shifted index.\n\n        See Also\n        --------\n        Series.shift : Shift values of Series.\n\n        Notes\n        -----\n        This method is only implemented for datetime-like index classes,\n        i.e., DatetimeIndex, PeriodIndex and TimedeltaIndex.\n\n        Ex

In [480]:
data = pd.Float64Index([1,2,3,4])
data.size

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3518886671.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


4

In [483]:
data = pd.Float64Index([1,2,3,4])
data.slice_indexer()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1690094017.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


slice(0, 4, None)

In [486]:
data = pd.Float64Index([1,2,3,4])
data.slice_locs()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\2485908127.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


(0, 4)

In [495]:
data = pd.Float64Index([1,2,3,4])
data.sort.__doc__

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\2382138229.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


'\n        Use sort_values instead.\n        '

In [499]:
data = pd.Float64Index([1,2,3,4])
data.sort_values(ascending=False)

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1469576952.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


Float64Index([4.0, 3.0, 2.0, 1.0], dtype='float64')

In [502]:
data = pd.Float64Index([1,2,3,4])
data.sortlevel(ascending=False)

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\465556438.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([1,2,3,4])


(Float64Index([4.0, 3.0, 2.0, 1.0], dtype='float64'),
 array([3, 2, 1, 0], dtype=int64))

In [514]:
data = pd.Float64Index([np.nan,1,2,3,4])
data.str

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\2759867395.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([np.nan,1,2,3,4])


In [520]:
data = pd.Float64Index([np.nan,1,2,3,4])
data.symmetric_difference(data.insert([1,2], [100,200]))

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1369228314.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([np.nan,1,2,3,4])


Float64Index([100.0, 200.0], dtype='float64')

In [525]:
data = pd.Float64Index([np.nan,1,2,3,4])
data.take([-1,0,3])

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1568992337.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([np.nan,1,2,3,4])


Float64Index([4.0, nan, 3.0], dtype='float64')

In [528]:
data = pd.Float64Index([np.nan,1,2,3,4])
data.to_flat_index()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\4011967910.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([np.nan,1,2,3,4])


Float64Index([nan, 1.0, 2.0, 3.0, 4.0], dtype='float64')

In [531]:
data = pd.Float64Index([np.nan,1,2,3,4])
data.to_frame()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3550417001.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([np.nan,1,2,3,4])


0
NaN  NaN
1.0  1.0
2.0  2.0
3.0  3.0
4.0  4.0

In [534]:
data = pd.Float64Index([np.nan,1,2,3,4])
data.to_list()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\2321130977.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([np.nan,1,2,3,4])


[nan, 1.0, 2.0, 3.0, 4.0]

In [537]:
data = pd.Float64Index([np.nan,1,2,3,4])
data.to_native_types()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1570506620.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([np.nan,1,2,3,4])
C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1570506620.py:2: FutureWarning: The 'to_native_types' method is deprecated and will be removed in a future version. Use 'astype(str)' instead.
  data.to_native_types()


array(['', '1.0', '2.0', '3.0', '4.0'], dtype='<U3')

In [545]:
data = pd.Float64Index([np.nan,1,2,3,4])
data.to_numpy()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\2077744662.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([np.nan,1,2,3,4])


array([nan,  1.,  2.,  3.,  4.])

In [547]:
data = pd.Float64Index([np.nan,1,2,3,4])
data.to_series()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\515808355.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([np.nan,1,2,3,4])


NaN    NaN
1.0    1.0
2.0    2.0
3.0    3.0
4.0    4.0
dtype: float64

In [548]:
data = pd.Float64Index([np.nan,1,2,3,4])
data.tolist()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\3102791978.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([np.nan,1,2,3,4])


[nan, 1.0, 2.0, 3.0, 4.0]

In [551]:
data = pd.Float64Index([np.nan,1,2,3,4])
data.transpose()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\2353959544.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([np.nan,1,2,3,4])


Float64Index([nan, 1.0, 2.0, 3.0, 4.0], dtype='float64')

In [556]:
data = pd.Float64Index([np.nan,1,2,3,4])
data.union(data.insert([1,2], [100,200]))

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1887249492.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([np.nan,1,2,3,4])


Float64Index([1.0, 2.0, 3.0, 4.0, 100.0, 200.0, nan], dtype='float64')

In [560]:
data = pd.Float64Index([np.nan,1,2,3,4,4])
data.unique()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\2252132817.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([np.nan,1,2,3,4,4])


Float64Index([nan, 1.0, 2.0, 3.0, 4.0], dtype='float64')

In [567]:
data = pd.Float64Index([np.nan,1,2,3,4,4])
data.value_counts()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1437261679.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([np.nan,1,2,3,4,4])


4.0    2
1.0    1
2.0    1
3.0    1
dtype: int64

In [569]:
data = pd.Float64Index([np.nan,1,2,3,4,4])
data.values

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\1429866033.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([np.nan,1,2,3,4,4])


array([nan,  1.,  2.,  3.,  4.,  4.])

In [571]:
data = pd.Float64Index([np.nan,1,2,3,4,4])
data.view()

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\2951707021.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([np.nan,1,2,3,4,4])


Float64Index([nan, 1.0, 2.0, 3.0, 4.0, 4.0], dtype='float64')

In [576]:
data = pd.Float64Index([np.nan,1,2,3,4,4])
data.where(data==2)

C:\Users\student.ASTRUM-DOMAIN\AppData\Local\Temp\ipykernel_12788\918610403.py:1: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  data = pd.Float64Index([np.nan,1,2,3,4,4])


Float64Index([nan, nan, 2.0, nan, nan, nan], dtype='float64')